package hostsurface

import (
	"fmt"
	"io/fs"
	"sort"
	"strings"
	"testing"

	"github.com/mnemon-dev/mnemon/harness/internal/assets"
)

var (
	hookgenHosts = []string{"claude-code", "codex"}
	hookgenLoops = []string{"memory", "skill"}
)

// parityPatches is the ONLY sanctioned escape hatch from byte parity: per legacy file, a table of
// LITERAL oldFragment -> newFragment replacements applied to the legacy bytes before comparing
// against the generated hook. Each old fragment must occur exactly once, so a patch can never
// silently widen. The table is empty: the generator reproduces all 16 legacy hooks byte-for-byte.
// Any future intentional divergence (e.g. the claude bare-interpolation escape fix, which is a
// LATER task) must land here as a recorded literal diff AND in patchedFiles below.
var parityPatches = map[string]map[string]string{}

// patchedFiles enumerates the files that are EXPECTED to carry non-empty patches. Asserting this
// set (instead of just tolerating whatever parityPatches contains) keeps the whitelist from
// becoming a drift backdoor: adding a patch without enumerating the file here fails the test.
var patchedFiles = []string{}

// TestGeneratedHooksMatchLegacyByteForByte is the stage-3 acceptance bar: for every
// (host, loop, timing) the generator must reproduce the hand-written legacy hook shell
// byte-for-byte (trailing newlines, blank lines, comments, wording — everything).
func TestGeneratedHooksMatchLegacyByteForByte(t *testing.T) {
	for _, host := range hookgenHosts {
		for _, loop := range hookgenLoops {
			for _, timing := range hookTimings {
				legacyPath := "hosts/" + host + "/" + loop + "/hooks/" + timing + ".sh"
				t.Run(legacyPath, func(t *testing.T) {
					legacyBytes, err := fs.ReadFile(assets.FS, legacyPath)
					if err != nil {
						t.Fatalf("read legacy hook %s: %v", legacyPath, err)
					}
					expected := string(legacyBytes)
					for _, old := range sortedKeys(parityPatches[legacyPath]) {
						if n := strings.Count(expected, old); n != 1 {
							t.Fatalf("patch fragment for %s occurs %d times (must be exactly 1):\n%s", legacyPath, n, old)
						}
						expected = strings.Replace(expected, old, parityPatches[legacyPath][old], 1)
					}
					generated, err := RenderHook(loop, host, timing)
					if err != nil {
						t.Fatalf("RenderHook(%s, %s, %s): %v", loop, host, timing, err)
					}
					if generated != expected {
						t.Fatalf("generated hook diverges from legacy %s:\n%s", legacyPath, describeDivergence(expected, generated))
					}
				})
			}
		}
	}

	// The set of files with non-empty patches must equal the explicitly enumerated set — no
	// silent whitelist growth.
	var withPatches []string
	for path, patches := range parityPatches {
		if len(patches) > 0 {
			withPatches = append(withPatches, path)
		}
	}
	sort.Strings(withPatches)
	expectedPatched := append([]string(nil), patchedFiles...)
	sort.Strings(expectedPatched)
	if strings.Join(withPatches, ",") != strings.Join(expectedPatched, ",") {
		t.Fatalf("files with patches %v != enumerated patched set %v", withPatches, expectedPatched)
	}
}

// describeDivergence renders a unified-diff-style line view plus a byte-offset context around the
// first divergence, so a parity failure is debuggable from the test log alone.
func describeDivergence(expected, generated string) string {
	var b strings.Builder
	expLines := strings.Split(expected, "\n")
	genLines := strings.Split(generated, "\n")
	line := 0
	for line < len(expLines) && line < len(genLines) && expLines[line] == genLines[line] {
		line++
	}
	fmt.Fprintf(&b, "first divergent line: %d\n", line+1)
	for i := max(0, line-2); i < line && i < len(expLines); i++ {
		fmt.Fprintf(&b, "  %q\n", expLines[i])
	}
	for i := line; i < min(line+3, len(expLines)); i++ {
		fmt.Fprintf(&b, "- %q\n", expLines[i])
	}
	for i := line; i < min(line+3, len(genLines)); i++ {
		fmt.Fprintf(&b, "+ %q\n", genLines[i])
	}
	offset := 0
	for offset < len(expected) && offset < len(generated) && expected[offset] == generated[offset] {
		offset++
	}
	fmt.Fprintf(&b, "first divergent byte offset: %d\n", offset)
	fmt.Fprintf(&b, "expected bytes:  %s\n", hexContext(expected, offset))
	fmt.Fprintf(&b, "generated bytes: %s\n", hexContext(generated, offset))
	return b.String()
}

func hexContext(s string, offset int) string {
	start := max(0, offset-8)
	end := min(len(s), offset+8)
	var b strings.Builder
	for i := start; i < end; i++ {
		if i == offset {
			b.WriteString("|")
		}
		fmt.Fprintf(&b, "%02x ", s[i])
	}
	if offset >= len(s) {
		b.WriteString("|<EOF>")
	}
	return b.String()
}

// TestHookgenDeterministic renders all 16 hooks twice and requires byte equality: the generator
// must be a pure function of (intents, mechanics) — no time, no environment, no map order.
func TestHookgenDeterministic(t *testing.T) {
	for _, host := range hookgenHosts {
		for _, loop := range hookgenLoops {
			for _, timing := range hookTimings {
				first, err := RenderHook(loop, host, timing)
				if err != nil {
					t.Fatalf("RenderHook(%s, %s, %s) first render: %v", loop, host, timing, err)
				}
				second, err := RenderHook(loop, host, timing)
				if err != nil {
					t.Fatalf("RenderHook(%s, %s, %s) second render: %v", loop, host, timing, err)
				}
				if first != second {
					t.Fatalf("RenderHook(%s, %s, %s) is not deterministic:\n%s", loop, host, timing, describeDivergence(first, second))
				}
			}
		}
	}
}

// --- fail-closed decode tests: the vocabulary is a CLOSED set, unknown members must error ---

const validMinimalIntents = `{"schema_version":1,"hooks":{"remind":{"response":{"role":"one-liner","text":"hello"}}}}`

func TestDecodeHookIntentsFailClosed(t *testing.T) {
	cases := map[string]string{
		"unknown timing": `{"schema_version":1,"hooks":{"bogus":{"response":{"role":"one-liner","text":"x"}}}}`,
		"unknown gate type": `{"schema_version":1,"hooks":{"nudge":{"gates":[{"type":"wormhole"}],
			"response":{"role":"one-liner","text":"x"}}}}`,
		"unknown section type":  `{"schema_version":1,"hooks":{"prime":{"sections":[{"type":"telemetry"}]}}}`,
		"unknown json field":    `{"schema_version":1,"hooks":{"remind":{"responze":{"role":"one-liner","text":"x"}}}}`,
		"trailing json":         validMinimalIntents + `{}`,
		"wrong schema version":  `{"schema_version":2,"hooks":{"remind":{"response":{"role":"one-liner","text":"x"}}}}`,
		"unknown response role": `{"schema_version":1,"hooks":{"remind":{"response":{"role":"shout","text":"x"}}}}`,
		"unknown threshold metric": `{"schema_version":1,"hooks":{"compact":{"gates":[{"type":"threshold",
			"metric":"entropy","cmp":"gt","limit_env":"X","limit_default":"1"}],
			"response":{"role":"message","text":"x"}}}}`,
		"unknown threshold cmp": `{"schema_version":1,"hooks":{"compact":{"gates":[{"type":"threshold",
			"metric":"usage-event-count","cmp":"lt","file_env":"X","file_default":"y","limit_env":"Z","limit_default":"1"}],
			"response":{"role":"message","text":"x"}}}}`,
		"gate param on wrong type": `{"schema_version":1,"hooks":{"nudge":{"gates":[{"type":"if-input-field",
			"field":"stop_hook_active","marker":"prime"}],"response":{"role":"one-liner","text":"x"}}}}`,
		"select without threshold": `{"schema_version":1,"hooks":{"nudge":{"response":{"role":"message",
			"over":"a","under":"b"}}}}`,
		"shell-active slot text": `{"schema_version":1,"hooks":{"remind":{"response":{"role":"one-liner",
			"text":"hi $(rm -rf /)"}}}}`,
	}
	for name, raw := range cases {
		if _, err := decodeHookIntents([]byte(raw)); err == nil {
			t.Errorf("%s: decodeHookIntents accepted invalid input", name)
		}
	}
	if _, err := decodeHookIntents([]byte(validMinimalIntents)); err != nil {
		t.Errorf("valid minimal intents rejected: %v", err)
	}
}

func TestDecodeHostMechanicsFailClosed(t *testing.T) {
	wrap := func(mechanics string) []byte {
		return []byte(`{"schema_version":2,"name":"x","mechanics":` + mechanics + `}`)
	}
	valid := `{"stdin_read":{"default":"tolerant"},"dialect":{"default":"plain"},"json_escape":false}`
	cases := map[string][]byte{
		"missing mechanics":   []byte(`{"schema_version":2,"name":"x"}`),
		"unknown stdin idiom": wrap(`{"stdin_read":{"default":"buffered"},"dialect":{"default":"plain"},"json_escape":false}`),
		"unknown dialect":     wrap(`{"stdin_read":{"default":"strict"},"dialect":{"default":"yaml"},"json_escape":false}`),
		"unknown json field":  wrap(`{"stdin_read":{"default":"strict"},"dialect":{"default":"plain"},"json_escape":false,"shell":"zsh"}`),
		"trailing json":       wrap(valid + `{}`),
		"unknown override timing": wrap(`{"stdin_read":{"default":"strict","overrides":{"memory":{"boot":"tolerant"}}},
			"dialect":{"default":"plain"},"json_escape":false}`),
		"unknown override value": wrap(`{"stdin_read":{"default":"strict","overrides":{"memory":{"nudge":"buffered"}}},
			"dialect":{"default":"plain"},"json_escape":false}`),
		"unknown wording slot": wrap(`{"stdin_read":{"default":"strict"},"dialect":{"default":"plain"},"json_escape":false,
			"wording_overrides":{"memory":{"remind":{"texxt":"hi"}}}}`),
		"unknown marker timing": wrap(`{"stdin_read":{"default":"strict"},"dialect":{"default":"plain"},"json_escape":false,
			"marker_overrides":{"memory":{"boot":false}}}`),
	}
	for name, raw := range cases {
		if _, err := decodeHostMechanics(raw); err == nil {
			t.Errorf("%s: decodeHostMechanics accepted invalid input", name)
		}
	}
	if _, err := decodeHostMechanics(wrap(valid)); err != nil {
		t.Errorf("valid minimal mechanics rejected: %v", err)
	}
}

// RenderHook itself must fail closed on unknown coordinates: a misspelled timing or loop cannot
// fall back to an empty hook.
func TestRenderHookFailClosed(t *testing.T) {
	if _, err := RenderHook("memory", "codex", "boot"); err == nil {
		t.Error("unknown timing accepted")
	}
	if _, err := RenderHook("nonexistent", "codex", "prime"); err == nil {
		t.Error("unknown loop accepted")
	}
	if _, err := RenderHook("memory", "nonexistent", "prime"); err == nil {
		t.Error("unknown host accepted")
	}
}
